-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 14-01-2025 a las 17:20:25
-- Versión del servidor: 5.7.44
-- Versión de PHP: 8.1.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `solestamx_prod`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `locales`
--

CREATE TABLE `locales` (
  `id` int(11) NOT NULL,
  `nombre` varchar(150) NOT NULL,
  `planta` enum('panta alta','planta baja') NOT NULL DEFAULT 'panta alta',
  `numero_local` int(11) NOT NULL,
  `descripcion` text,
  `telefono_1` varchar(25) DEFAULT NULL,
  `telefono_2` varchar(25) DEFAULT NULL,
  `whatsapp` varchar(25) NOT NULL,
  `telefono_atencion_clientes` varchar(25) NOT NULL,
  `correo_electronico` varchar(50) DEFAULT NULL,
  `ubicacion` varchar(150) DEFAULT NULL,
  `url_ubicacion` varchar(150) DEFAULT NULL,
  `url_pagina` varchar(150) DEFAULT NULL,
  `url_facebook` varchar(64) DEFAULT NULL,
  `url_instagram` varchar(64) DEFAULT NULL,
  `url_twitter` varchar(50) DEFAULT NULL,
  `url` varchar(50) DEFAULT NULL,
  `estatus` enum('activo','suspendido') NOT NULL DEFAULT 'suspendido',
  `fecha_registro` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `locales`
--

INSERT INTO `locales` (`id`, `nombre`, `planta`, `numero_local`, `descripcion`, `telefono_1`, `telefono_2`, `whatsapp`, `telefono_atencion_clientes`, `correo_electronico`, `ubicacion`, `url_ubicacion`, `url_pagina`, `url_facebook`, `url_instagram`, `url_twitter`, `url`, `estatus`, `fecha_registro`) VALUES
(1, 'CARBÓN CENTRAL DE HAMBURGUESAS', 'planta baja', 118, 'Hamburguesas y coctelería.', '2226227642', NULL, '2212004337', '', NULL, NULL, NULL, 'carbonhamburguesas.com', 'https://www.facebook.com/CarbonSolesta', 'https://www.instagram.com/carboncentraldehamburgue', NULL, 'carbon_central_de_hamburguesas', 'suspendido', '2020-11-13 14:55:07'),
(2, 'EL GRAN ROSTICERO', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'el_gran_rosticero', 'suspendido', '2020-11-13 14:55:07'),
(3, 'EL TEAPANECO', 'planta baja', 125, 'El Teapaneco es el restaurante de comida regional más popular en Villahermosa, Tabasco.\r\n\r\nComida de villahermosa.', '2222146691', NULL, '', '', NULL, NULL, NULL, 'elteapaneco.com', 'https://www.facebook.com/El-Teapaneco-Puebla-268224277138518', 'https://www.instagram.com/elteapanecopuebla', 'https://twitter.com/el_teapaneco', 'el_teapaneco', 'suspendido', '2020-11-13 14:55:07'),
(4, 'LE MACARON', 'planta baja', 114, 'Le Macaron Boutique dedicados a la alta repostería francesa.\r\n\r\nBoutique de macarrones.', '5580961459', NULL, '', '', 'ventas@lemacaron.mx', NULL, '', 'lemacaron.mx', 'https://www.facebook.com/LeMacaronBoutique', 'https://www.instagram.com/lemacaronboutique', 'https://twitter.com/lemacaronb', 'le_macaron', 'suspendido', '2020-11-13 14:55:07'),
(5, 'OCHO30', 'planta baja', 113, 'Es un centro de reunión y placer, un espacio cultural abierto, donde queremos consentir tus sentidos, satisfacer tus instintos y dar muerte a la razón. OCHO30 es un espacio de encuentro, donde las contradicciones están a la orden del día mientras las situaciones se acarician, rozan, chocan y se yuxtaponen.\r\n\r\nBuen café, postres, cocina urbana, ambiente ecléctico y plural.', '2222146679', NULL, '2221827404', '', 'info@ocho30.com', NULL, NULL, 'ocho30.com', 'https://www.facebook.com/ocho30cafe', 'https://www.instagram.com/ocho30cafe', NULL, 'ocho30', 'activo', '2020-11-13 14:55:07'),
(6, 'PIANO', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'piano', 'suspendido', '2020-11-13 14:55:07'),
(7, 'SANTITO MAÍZ & AGAVE', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'santito_maiz_y_agave', 'suspendido', '2020-11-13 14:55:07'),
(8, 'SHIRUSHI', 'planta baja', 124, 'Shirushi es un restaurante de comida japonesa y de fusión cuya fundación data del año 1993. nuestra propuesta gastronómica se basa en la cocina tradicional japonesa tropicalizada al paladar mexicano.', '2229456982', NULL, '', '2228014241', NULL, NULL, NULL, 'linktr.ee/SHIRUSHI_MX', 'https://www.facebook.com/shirushimex', 'https://www.instagram.com/shirushi_puebla', 'https://twitter.com/shirushi_mx', 'shirushi', 'activo', '2020-11-13 14:55:07'),
(9, 'TRIPOLI', 'planta baja', 116, NULL, '2222146675', NULL, '', '2221991123', 'tripolizav@gmail.com', NULL, NULL, 'tripoli.mx', 'https://www.facebook.com/TacosTripoli', 'https://www.instagram.com/tacostripoli', NULL, 'tripoli', 'suspendido', '2020-11-13 14:55:07'),
(10, 'AUGURIO', 'panta alta', 0, 'Adéntrate en los sabores de México y de la cocina poblana de la mano del chef Ángel Vázquez, que ofrece una experiencia culinaria que no sólo se degusta, sino que especialmente se siente.', '2222272909', NULL, '', '', NULL, NULL, 'goo.gl/maps/vJxtYARE8gNfjqCW7', 'augurio.mx', 'facebook.com/AugurioRestaurante', 'instagram.com/augurio.restaurante', NULL, 'augurio', 'suspendido', '2020-11-13 14:55:07'),
(11, 'BIANCOLATTE', 'panta alta', 0, 'Postres helados. Todos los días nuestro gelato es preparado con cuidado y dedicación usando únicamente ingredientes elegidos de primera calidad, lo que genera su textura cremosa y sabor inigualable. Biancolatte no utiliza colorantes, saborizantes o aditivos artificiales, no lo hemos hecho nunca y no lo haremos jamás.', '2213243001', NULL, '2213243001', '', 'biancolattemx@gmail.com', NULL, NULL, 'biancolatte.mx', 'https://www.facebook.com/BiancolatteMX', 'https://www.instagram.com/biancolattemx', 'https://twitter.com/biancolattemx', 'biancolatte', 'suspendido', '2020-11-13 14:55:07'),
(12, 'CABANNA', 'panta alta', 0, 'Restaurante Botanero y Casua. Cabanna nace en Culiacán Sinaloa en el 2012, bajo un concepto Coqueto y Casual, como un lugar para disfrutar y compartir entre amigos en un ambiente relajado que te transporta a la playa', '2222146736', '2223270853', '', '', 'puebla@cabanna.com.mx', NULL, 'g.page/cabanna--puebla-mariscos', 'cabanna.com.mx', 'https://www.facebook.com/CABANNA.REST', 'https://www.instagram.com/cabannarestaurant', 'https://twitter.com/cabanna_rest', 'cabanna', 'activo', '2020-11-13 14:55:07'),
(13, 'CITY MARKET CAFÉ', 'panta alta', 0, 'Descubre y prueba en un solo lugar 36 variedades de los más finos granos de café, servidos por baristas profesionales a una temperatura exacta para extraer los mejores sabores y aromas de este ‘oro negro’.', NULL, NULL, '', '', NULL, NULL, 'goo.gl/maps/SDASo5YJvwSETsNv6', 'citymarketcafe.com.mx', NULL, NULL, NULL, 'city_market_cafe', 'suspendido', '2020-11-13 14:55:07'),
(14, 'CREPE CORNER', 'planta baja', 0, 'Crepas dulces y saladas. Crêpe Corner es un delicioso concepto de crepería, que combina los mejores y más frescos ingredientes para confeccionar exquisitas crepas dulces y saladas', '222 214 6649', NULL, '', '', 'contact@crepecorners.com', NULL, NULL, 'crepecorners.com', 'https://www.facebook.com/crepecornerssolesta', 'https://www.instagram.com/crepecorners', 'https://twitter.com/crepecorner', 'crepe_corner', 'suspendido', '2020-11-13 14:55:07'),
(15, 'EL FUEGO DULCE', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'el_fuego_dulce', 'suspendido', '2020-11-13 14:55:07'),
(16, 'GUXI', 'planta baja', 0, NULL, '2225630783', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'guxi', 'activo', '2020-11-13 14:55:07'),
(17, 'LA CHICATANA', 'panta alta', 0, 'Comida mexicana. Cantina contemporánea, sibarita, sofisticada, ecléctica. Punto de encuentro y hermandad. Cultura, gastronomía y memoria. Orgullo de tacos, salsas, ceviches, tequilas, vinos y mezcales.', '2226227513', NULL, '', '2211122241', 'contacto@lachicatana.com', NULL, 'g.page/lachicatana', 'lachicatana.com', 'https://www.facebook.com/lachicatanarestaurante', 'https://www.instagram.com/lachicatanarestaurante', NULL, 'la_chicatana', 'suspendido', '2020-11-13 14:55:07'),
(18, 'LAS ALITAS', 'panta alta', 65, 'En Las Alitas te ofrecemos una experiencia única basada en: la calidad de alimentos, un servicio que vuela, la ambientación, la música, y nuestros característicos rituales.\r\n\r\nRestaurante  con variedad de alimentos y bebidas.', '2222146734', NULL, '2215637578', '', 'puebla_solesta@lasalitas.com', NULL, 'goo.gl/maps/b87AfrreTqrd5PUE6', 'lasalitas.com', 'https://www.facebook.com/LasAlitasPue', 'https://www.instagram.com/lasalitas_oficial', 'https://twitter.com/lasalitas', 'las_alitas', 'activo', '2020-11-13 14:55:07'),
(19, 'MOCHOMOS', 'panta alta', 5, 'Mochomos® es un restaurante - bar que ofrece un nuevo concepto gastronómico con base a la creatividad y gustos de la cocina Sonorense de autor, una cocina honesta que mezcla los mejores sabores, colores y texturas para ofrecerte un amplio menú de entradas, carnes, pescados y mariscos de la mas alta calidad así como vinos de la región y etiquetas nacionales e internacionales reconocidas a nivel mundial para el paladar mas exigente.\r\n\r\nEn el que se invita a probar de todo y a compartir al centro para tener una experiencia gastronómica completa en medio de un ambiente cómodo y agradable, siempre con un servicio inigualable.\r\n\r\nMochomos Puebla te espera con instalaciones de primer nivel, privados que cuidan al máximo sus detalles y una terraza única con un ambiente incomparable. ', '2222146728', '2211127702', '', '', 'mochomos.puebla@grupocosteno.com', NULL, 'g.page/mochomospuebla', 'https://mochomos.mx/index2.php', 'https://www.facebook.com/mochpuebla', 'https://www.instagram.com/mochomospuebla/', 'https://twitter.com/MochomosCDMX', 'mochomos', 'activo', '2020-11-13 14:55:07'),
(20, 'MOYO', 'panta alta', 0, 'Moyo es un alimento funcional por su importante contenido de nutrientes  que favorecen el óptimo funcionamiento del organismo.\r\n<br><br>\r\nEl helado de moyo es todo un arte gracias a sus procesos artesanales, buscamos diario la fruta fresca del mercado, la cual es picada día a día con el fin de conservar toda su frescura y nutrientes.', NULL, NULL, '', '', 'https://www.moyo.com.mx', NULL, NULL, NULL, 'https://www.facebook.com/MoyoYogurt', 'https://www.instagram.com/moyoyogurt', 'https://twitter.com/moyoyogurt', 'moyo', 'activo', '2020-11-13 14:55:07'),
(21, 'SANTA CLARA', 'panta alta', 0, 'Lácteos deliciosos y una tradición que se conserva desde 1924. Siempre que pruebes Santa Clara te darás cuenta de los ingredientes de la más alta calidad y del trabajo y cuidado a los detalles.', NULL, NULL, '', '', NULL, NULL, NULL, NULL, 'https://www.facebook.com/SantaClaraMex', 'https://www.instagram.com/santaclaramx', NULL, 'santa_clara', 'activo', '2020-11-13 14:55:07'),
(22, 'SERATTA', 'panta alta', 6, 'Restaurante, Cafetería, Bar, Arguilería. Seratta Solesta es un café - restaurante que brinda el mejor servicio y alta calidad en sus productos.', '2222146647', '2222839501', '2211167457', '522213220480', 'relacionespublicas@gruposeratta.mx', NULL, 'https://goo.gl/maps/piaNeSqn1EGw5iMH9', 'gruposeratta.mx', 'https://www.facebook.com/SerattaSolesta', 'https://instagram.com/serattamx', 'https://twitter.com/SerattaCafe', 'seratta', 'activo', '2020-11-13 14:55:07'),
(23, 'SONORA GRILL', 'panta alta', 64, 'Steakhouse mexicano que fusiona lo moderno con lo acogedor, ideal para degustar exquisitos cortes de carne con calidad Sterling Silver Y sorprendente mixología que combina sensaciones y sabores.', '2222146782', '2222146783', '221 228 3844', '', 'contacto@sggroup.com.mx', NULL, 'https://g.page/SonoraGrill-Solesta', 'sonoragrill.com.mx', 'https://www.facebook.com/SonoraGrillMx', 'https://www.instagram.com/sonoragrill', 'https://twitter.com/sonoraggroup', 'sonora_grill', 'activo', '2020-11-13 14:55:07'),
(24, 'STARBUCKS', 'panta alta', 2, 'La personas reciben un servicio genuino, un ambiente acogedor y una magnífica taza de café tostado preparado con esmero por manos expertas.', '8002880888', NULL, '', '018002880888', 'tuopinion@starbucks.com.mx', NULL, 'https://goo.gl/maps/KuvdZwDeUTmPcpAz8', 'starbucks.com.mx', 'https://www.facebook.com/StarbucksMexico', 'https://www.instagram.com/starbucksmex', 'https://twitter.com/StarbucksMex', 'starbucks', 'activo', '2020-11-13 14:55:07'),
(25, 'SUNTORY', 'planta baja', 12, 'RESTAURANTE SUNTORY SON PARTE DE UN HOLDING JAPONES QUE ABREIO HACE MAS DE 40 AÑOS EN MEXICO, SU PRIMER RESTAURANTE EN EL MUNDO. LA CALIDAD Y SU REFINADA TRADICION CULINARIA, HAN SITUADO A SUNTORY ENTRE LOS MAS DESTACADOS RESTAURANTES DE NUESTRO PAIS, YA QUE A TRAVES DE LOS AÑOS HA INNOVADO SU DISTINGUIDO CONCEPTO CULTURAL, OFRECIENDO UN EXQUISITO SINCRETISMO GASTRONOMICO PARA EL PALADAR MEXICANO, PERO CONCERVANDO EL ARTE Y LAS DELICIAS DE LA ALTA COCINA DEL JAPON.', '2222570948', NULL, '', '2222570946', 'mgarcia@suntory.com.mx', 'goo.gl/maps/MGTykSXW14SD2KXy9', NULL, 'suntory.com.mx', 'https://www.facebook.com/RestaurantesSuntory', 'https://www.instagram.com/suntorymexico', 'https://twiter.com/suntoryrest', 'suntory', 'activo', '2020-11-13 14:55:07'),
(26, 'TARLETS COFFEE', 'panta alta', 0, 'Somos una empresa gastronómica dedicada a la elaboración de alimentos y postres.\r\n<br><br>\r\nCon la originalidad de la fusión de la alta cocina francesa e italiana y el propósito de satisfacer con su sabor, frescura y calidad los paladares más exigentes.', '2221697169', NULL, '', '', 'info@tarletscoffee.com.mx', NULL, NULL, 'tarletscoffee.com.mx', 'https://www.facebook.com/Tarletscoffee.cafeteria', 'https://www.instagram.com/tarletscoffeemx', 'https://twitter.com/tarletscoffeemx', 'tarlets_coffee', 'activo', '2020-11-13 14:55:07'),
(27, 'TOKS', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'toks', 'suspendido', '2020-11-13 14:55:07'),
(28, 'SOMA SOCIAL KITCHEN', 'panta alta', 0, 'Primer Matcha Bar en Puebla. Cocina consciente, listos para ofrecerte una experiencia única.', NULL, NULL, '', '', NULL, NULL, 'https://g.page/verdematchabar', NULL, 'https://www.facebook.com/VerdeMatchaBar', 'https://www.instagram.com/verdematchabar', NULL, 'soma', 'suspendido', '2020-11-13 14:55:07'),
(29, 'ALBOA', 'planta baja', 127, 'Alboa se ha posicionado desde el año 2012 como el único concepto de entretenimiento que integra juegos, como: billar y boliche; gastronomía y mixología; los mejores eventos deportivos y música en vivo en un solo lugar.\r\n\r\nAlboa amplía su oferta con la apertura de un recinto en el C.C. Solesta, convirtiéndose en el primer complejo de la marca en Puebla, que ofrece un concepto de Entertainment Hall para brindar una experiencia de entretenimiento única en México, al contar con una gran variedad de actividades para que la diversión nunca termine.\r\n\r\nAlboa Solesta representa para la marca su continuación con el plan de expansión a nivel nacional, a través de una ubicación clave -como lo es Puebla- para llevar a más lugares un concepto de entretenimiento inigualable.\r\n\r\nAlboa Solesta cuenta con 10 pistas de boliche con capacidad para 60 personas. Este complejo es de los primeros en tener pistas híbridas conformadas por profesionales de Brunswick; y el mejor equipo electrónico de Qubica AMF, marcas líderes de boliche a nivel mundial.\r\n\r\nEl Sports Bar tiene un aforo para más de 200 personas sentadas, quienes podrán disfrutar de un video wall de 10 x 5.5 metros de pantalla led pitch 3.9; para garantizar que el espectador tenga una experiencia envolvente durante la transmisión de los mejores eventos deportivos\r\n\r\nEl recinto cuenta con un sistema lineal para concierto VTX A8, y un espacio acondicionado con materiales especiales para asegurar el correcto comportamiento del audio, logrando una acústica absorbente.\r\n\r\nAlboa Live en Solesta es uno de los conceptos que forman parte de Alboa. Se trata de un espacio dedicado exclusivamente a la oferta musical de los géneros pop y rock, en su mayoría, que sin duda envolverá los sentidos de hasta 500 espectadores de pie.\r\nEl primer nivel del complejo cuenta con una cómoda zona de palcos para más de 52 personas, con una excelente vista al escenario, desde donde se podrá vivir al máximo la oferta de contenido musical a partir de diciembre.\r\n\r\nAdicional, Alboa Solesta ofrece a sus visitantes 1 terraza con capacidad para 24 personas, donde podrán disfrutar de la gran vista que posee.\r\n\r\nAdemás, los visitantes de Alboa Solesta podrán sorprenderse con su deliciosa oferta gastronómica; en donde el público podrá deleitarse con un amplio catálogo de pizzas y alitas. Y para acompañar, la barra ofrece una extensa gama de mixología de cualquier tipo, gracias a las alianzas con marcas del segmento de bebidas alcohólicas premium más grandes de México.', '2215960799', NULL, '', '2215960799', 'alboasolesta@alboa.com.mx', NULL, NULL, 'alboa.com.mx', 'www.facebook.com/AlboaOficial', 'www.instagram.com/alboaoficial', 'twitter.com/AlboaMX', 'alboa', 'activo', '2020-11-13 14:55:07'),
(30, 'ARENA', 'panta alta', 0, 'La introducción de los videojuegos como nunca antes lo has experimentado. Cientos de títulos en videojuegos y opciones para todos los gustos, sumérgete en el mundo gamer y forma parte de la experiencia Arena.', '2229458625', NULL, '', '', 'atencionaclientes@arenatheplacetoplay.com', NULL, 'https://goo.gl/maps/WhuA4o7QugQp8vPs9', 'gamersarena.com.mx', 'https://www.facebook.com/ArenaThePlaceToPlay', 'https://www.instagram.com/arenatheplacetoplay', 'https://twitter.com/arenaplace2play', 'arena', 'suspendido', '2020-11-13 14:55:07'),
(31, 'CINEMEX', 'panta alta', 0, 'Disfrutar La Magia del Cine en salas con butacas más grandes que te proporcionarán mayor comodidad y con mayor privacidad entre butaca y butaca, únicas en México y un concepto exclusivo de Cinemex.', NULL, NULL, '', '', NULL, NULL, NULL, 'cinemex.com', 'https://www.facebook.com/Cinemex', 'https://www.instagram.com/cinemex', 'https://twitter.com/cinemex', 'cinemex', 'activo', '2020-11-13 14:55:07'),
(32, 'GAMERS', 'panta alta', 0, 'Si te encantan los videojuegos, no te pierdas las promociones, preventas, lanzamientos, noticias, tops y más. Juega con Gamers, juega más.', NULL, NULL, '', '', NULL, NULL, NULL, 'NULL', 'https://www.facebook.com/GamersRetail', NULL, 'https://twitter.com/GamersRetail', 'gamers', 'suspendido', '2020-11-13 14:55:07'),
(33, 'HOBBIES', 'panta alta', 0, 'Tienda de rompecabezas y juegos de mesa en la ciudad de Puebla. Juegos didácticos, cubo de Rubik, rompecabezas, juegos de mesa y toda la diversión.', NULL, NULL, '', '', NULL, NULL, NULL, NULL, 'https://www.facebook.com/hobbiespuebla', NULL, NULL, 'hobbies', 'activo', '2020-11-13 14:55:07'),
(34, 'JUGUETRÓN', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'juguetron', 'suspendido', '2020-11-13 14:55:07'),
(35, 'KID\'S UNIVERSE', 'panta alta', 0, 'Centro de entretenimiento con múltiples atracciones aptas para las diferentes edades, excelente música ambiental, cafetería y 6 certificaciones de seguridad que garantizan la mejor diversión y tranquilidad en un solo lugar.', NULL, NULL, '', '', 'contacto@kidsuniverse.mx', NULL, NULL, 'kidsuniverse.mx', 'https://www.facebook.com/KidsUniversePuebla', 'https://www.instagram.com/kids_universe_puebla', NULL, 'kids_universe', 'activo', '2020-11-13 14:55:07'),
(36, 'ADIDAS ORIGINALS', 'panta alta', 51, 'Descubre la variedad de tenis y ropa de última moda en adidas Originals, creados para darle a tu look casual, un toque único, versátil e imponente.', '2222907771', NULL, '', '50914712', NULL, NULL, NULL, 'adidas.mx/originals', 'https://www.facebook.com/adidasoriginals', 'https://www.instagram.com/adidasmx', 'https://twitter.com/adidasMX', 'adidas_originals', 'suspendido', '2020-11-13 14:55:07'),
(37, 'AMORISSIMI', 'panta alta', 77, 'La esencia de Amorissimi Baby & Kids es acercar a los pequeños a la moda, desde un recién nacido hasta un chico de 14 años. \r\nEn 2019, hemos decidido lanzar un nuevo segmento de mercado: Amorissimi Teens, el cual cuenta con colecciones modernas para niños y niñas que van desde los 9 hasta los 14 años.\r\nLas colecciones se conforman con prendas de gran calidad que siempre siguen las actuales tendencias del mercado donde la clase y la elegancia componen su esencia se transmite mediante artículos adaptados a las necesidades del día a día de los pequeños.\r\nPara nosotros es muy importante la calidad de nuestros productos, por lo que nuestros tejidos son seleccionados por expertos para asegurar el bienestar y confort, sin perder el estilo.\r\n¡Convertimos la moda en un auténtico juego de niños!', '2222570962', NULL, '', '2222570962', 'solesta@amorissimi.store', NULL, NULL, 'amorissimi.store', 'https://www.facebook.com/amorissimimx', 'https://www.instagram.com/amorissimimx', NULL, 'amorissimi', 'suspendido', '2020-11-13 14:55:07'),
(38, 'BABY MINK BOUTIQUE', 'panta alta', 85, 'Baby Mink Boutique. Baby Mink Boutique: Accesorios, Ropa Española, skip hop, calcetines, carters, avent, tomee teeppee, Relojes Pomo, Baby mink y Cobertores de adulto.\r\n\r\nManejamos una gran variedad de marcas de excelente calidad como son: Mayoral, Paz Rodriguez, Baby Mink, yoyo, Doona, Ezpz, Oribel, Tafstoys, Petunia, Shnuggle, Perh, Noomie, Copper Pearl, Ubbi y muchas mas.', '2222907723', NULL, '2223340714', '2222907723', 'babymink.solesta@hotmail.com', NULL, NULL, 'babyminkboutique.com', 'https://www.facebook.com/babyminkboutique', 'https://www.instagram.com/babyminkboutique', NULL, 'baby_mink_boutique', 'suspendido', '2020-11-13 14:55:07'),
(39, 'BOBOIS', 'planta baja', 0, 'Amantes de estilo. La moda Bobois está pensada para los amantes del estilo propio, que saben lucir cada día un look casual, distinguido y con clase.', NULL, NULL, '', 'contacto@bobois.com.mx', NULL, NULL, NULL, 'bobois.com.mx', 'https://www.facebook.com/CABANNA.REST', 'https://www.instagram.com/boboismx', NULL, 'bobois', 'activo', '2020-11-13 14:55:07'),
(40, 'BONNET Á POMPON', 'panta alta', 29, 'Marca de moda infantil española con inspiración francesa. El espíritu del “bohemian chic” renace para dar lugar al exclusivo estilo Bonnet à Pompon. Elegancia de inspiración francesa, con una marcada autenticidad que conecta con los niños y cuya máxima es la excelencia en la calidad y el cuidado por el detalle. Un carácter dulce, relajado y atractivo que favorece a los niños gracias a sus diseño de cortes impecables y colores exclusivos.', '2222907689', NULL, '', '2224606248', 'boutique.puebla@bonnetapompon.com', NULL, NULL, 'bonnetapompon.com', 'https://www.facebook.com/bonnetapompon.es', 'https://www.instagram.com/bonnetapompon_mx/', 'https://twitter.com/bonnetapompon', 'bonnet_a_pompon', 'suspendido', '2020-11-13 14:55:07'),
(41, 'CUIDADO CON EL PERRO', 'panta alta', 0, 'Marca de moda. Nuestro objetivo es ofrecer a un gran número de consumidores la mejor relación de calidad, moda y precio. Estamos inspirados constantemente por las tendencias mundiales y las transformamos para satisfacción de nuestro mercado.\r\n<br>\r\n<br>\r\nEn Cuidado con el Perro, el espíritu de juventud es nuestra fuente de inspiración y principal objetivo. Desde su creación en 2006, en Cuidado con el Perro hemos sabido adaptarnos a las necesidades de los jóvenes para ser hoy en día un claro referente de moda casual y desenfrenada en México.', NULL, NULL, '2227313547', '', 'atencionalcliente@cuidadoconelperro.com.mx', NULL, NULL, 'cuidadoconelperro.com.mx', 'https://www.facebook.com/OficialCCP', 'https://www.instagram.com/cuidadoconelperromx', 'https://twitter.com/ccperromx', 'cuidado_con_el_perro', 'activo', '2020-11-13 14:55:07'),
(42, 'EL COLUMPIO', 'panta alta', 0, 'Somos una empresa 100% mexicana dedicada a la venta de recuerdos artesanales, ropones, vestidos y accesorios para todo tipo de eventos sociales.\r\n\r\nProductos: Recuerdos, centros de mesa, ropones, vestidos, accesorios para bautizo y primera comunión.', '2222146666', NULL, '', '', 'contacto.elcolumpiomx@gmail.com', NULL, NULL, NULL, 'https://www.facebook.com/CeremoniasElColumpio', 'https://www.instagram.com/ceremoniaselcolumpio', NULL, 'el_columpio', 'activo', '2020-11-13 14:55:07'),
(43, 'FLEXI', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'flexi', 'suspendido', '2020-11-13 14:55:07'),
(44, 'FOREVER 21', 'panta alta', 0, 'Un cliente en Toronto, nombró a su hija Tiev Forever Golding porque estuvo a punto de dar a luz en una tienda Forever 21; una vez que expire su pasaporte solicitarán legalmente nombrarla \"FOREVER\". <br>El promedio de espacio de una tienda Forever 21 es de 3,500 metros cuadrados, la tienda más grande cuenta con 15,000 metros cuadrados, mientras que la primera tienda \"FASHION 21\" sólo cuenta con 83 metros cuadrados. <br>FASHION 21 logró ventas por $700,000 dólares en su primer año de operación mientras que los tres negocios previos que abrieron en ese local quebraron antes de cumplir su primer año. <br>Aún cuando la compañía se encuentra en una etapa de enorme crecimiento, el negocio se mantiene familiar.?', '2222907782', '5568020238', '', '8002255367', 'mxsupport@forever21.com', NULL, NULL, 'forever21.com.mx', 'https://www.facebook.com/Forever21MX', 'https://www.instagram.com/forever21mexico', 'https://twitter.com/F21MEX', 'forever_21', 'suspendido', '2020-11-13 14:55:07'),
(45, 'LEADS', 'panta alta', 0, 'La moda, el diseño y la inspiración deportiva en sneakers y el lifestyle. <br>Inspirar el sneaker lifestyle, ofreciendo artículos de la más alta calidad brindando siempre un servicio extraordinario y así contribuir con momentos felices en nuestros clientes.', '2222146721', NULL, '', '', NULL, NULL, NULL, NULL, 'https://www.facebook.com/leadsmx1', NULL, NULL, 'leads', 'suspendido', '2020-11-13 14:55:07'),
(46, 'LOB', 'panta alta', 0, 'La moda, el diseño y la inspiración deportiva en sneakers y el lifestyle. Inspirar el sneaker lifestyle, ofreciendo artículos de la más alta calidad brindando siempre un servicio extraordinario y así contribuir con momentos felices en nuestros clientes.', '2222155260', NULL, '2222146721', '', 't2leads@grupomva.com.mx', NULL, NULL, 'leadsmx.store', 'https://www.facebook.com/lob.com.mx', 'https://www.instagram.com/lobmoda', 'https://twitter.com/lobmoda', 'lob', 'activo', '2020-11-13 14:55:07'),
(47, 'LUBECK', 'panta alta', 0, 'Moda para caballeros. Lo mejor de la moda para caballeros está en Lubeck, pensada en hombres que saben imponer el estilo que refleja su personalidad', NULL, NULL, '', '', NULL, NULL, NULL, 'lubeck.mx', 'https://www.facebook.com/lubeckmoda', NULL, NULL, 'lubeck', 'suspendido', '2020-11-13 14:55:07'),
(48, 'MORAZUL', 'panta alta', 0, 'Zapatería de moda. Tienda boutique de calzado y accesorios, donde puedes encontrar las últimas tendencias y estilos para dama, caballero y el resto de la familia.', '2221411408', NULL, '', '', 'servicioacliente@pakar.com', NULL, NULL, 'tiendamoramora.com', 'https://www.facebook.com/coleccionmorazul', 'https://www.instagram.com/moramoracalzadoyaccesorios', NULL, 'morazul', 'suspendido', '2020-11-13 14:55:07'),
(49, 'ON RUNNING', 'panta alta', 53, 'On nació en los Alpes suizos con un objetivo: revolucionar la sensación al correr. Todo se basa en una idea radical. Aterrizajes suaves y despegues explosivos. O, como lo llamamos, correr sobre las nubes.', '2222146659', NULL, '2221138480', '2222146659', 'contacto@mtsport.com.mx ', NULL, 'awsports.mx', NULL, 'https://www.facebook.com/OnRunningMx', 'https://www.instagram.com/awsportsmx', 'https://twitter.com/on_runningmx', 'on_running', 'suspendido', '2020-11-13 14:55:07'),
(50, 'SOLÉ', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, 'https://www.facebook.com/modacalzadosole', NULL, NULL, 'sole', 'suspendido', '2020-11-13 14:55:07'),
(51, 'SOUL', 'panta alta', 25, 'Tienda especializada en calzado y ropa deportiva.', '2227627439', NULL, '2215842281', '2215842281', 'contacto@soul.com.mx', NULL, 'https://maps.app.goo.gl/jSX8CSeqyVMZVZrq9', 'soul.com.mx', 'https://www.facebook.com/SOULSNKRS', 'https://www.instagram.com/soulsnkrstore', 'https://twitter.com/soulsneakers', 'soul', 'activo', '2020-11-13 14:55:07'),
(52, 'SPORT MASTER', 'panta alta', 0, 'Empresa creada al 100% para deportistas. Inspirar la práctica del deporte y la actividad física, ofreciendo artículos deportivos de la más alta calidad, brindando siempre un servicio extraordinario y así contribuir en una sociedad más sana.', '2222907794', NULL, '', '', 'contacto@sportmasters.com.mx', NULL, NULL, 'sportmasters.com.mx', 'https://www.facebook.com/sportmasters.mx', 'https://www.instagram.com/sportmastersmx', NULL, 'sport_master', 'suspendido', '2020-11-13 14:55:07'),
(53, 'TAF', 'panta alta', 0, 'Cadena de sneakers más grande de lationoamerica y México. Líderes en el mercado de sneakers de moda y estilo de vida. Nos mueve la pasión y el gusto por los sneakers y por ello ofrecemos a nuestros clientes las marcas más reconocidas a nivel mundial.', '2222907734', NULL, '', '5568269462', 'servicioalcliente_taf@grupoaxo.com', NULL, NULL, 'taf.com.mx', 'https://www.facebook.com/tafmexico', 'https://www.instagram.com/tafmx', 'https://twitter.com/tafmx', 'tafs', 'suspendido', '2020-11-13 14:55:07'),
(54, 'URBAN STORE', 'panta alta', 0, 'Las mejores marcas a los mejores precios: Levis, Aeropostale, Roxy, Quiksilver, REWIND y más. Las mejores marcas, al mejor precio. Ven y arma tu #UrbanStyle.', '8000077066', NULL, '', '', NULL, NULL, 'urbanstore.com.mx', NULL, 'https://www.facebook.com/UbanStoreMX', 'https://www.instagram.com/urbanstoremx', 'https://twitter.com/UbanStoreMX', 'urban_store', 'activo', '2020-11-13 14:55:07'),
(55, 'VIANCI', 'panta alta', 0, 'Venta de lencería y trajes de baño para dama , multimarca exclusivas de importación , principalmente de origen Colombiano y Español.', '2222243030', NULL, '', '', 'laura.rosas@viancilingerie.com', NULL, NULL, NULL, 'https://www.facebook.com/VianciLenceria', 'https://www.instagram.com/viancipuebla', 'https://twitter.com/VianciStore', 'vianci', 'suspendido', '2020-11-13 14:55:07'),
(56, 'ANEL ET CHUY', 'panta alta', 0, 'Somos una cadena de salones de belleza con más de 30 años de experiencia. Constantemente nos estamos actualizando en tendencias de moda.', NULL, NULL, '', '', NULL, NULL, NULL, 'aneletchuygroupe.com', 'https://www.facebook.com/ACGroupeOficial', NULL, NULL, 'anel_et_chuy', 'activo', '2020-11-13 14:55:07'),
(57, 'EUROPIEL', 'panta alta', 69, 'Europiel es una empresa 100 % mexicana dedicada al cuidado de la piel especializada en depilación láser. Somos los pioneros en México –y uno de los pocos a nivel mundial– en usar el más nuevo, eficiente y seguro láser diodo.Somos la única empresa en el país que ofrece una garantía de eliminación de vello de hasta el 95 % en las zonas seleccionadas.\r\n\r\nVenta de paquetes de depilación laser.', '2226887342', NULL, '', '2226887342', 'contacto@europiel.com.mx ', NULL, NULL, 'europiel.com.mx', 'https://www.facebook.com/europiellaser', 'https://www.instagram.com/europiel_laser', NULL, 'europiel', 'activo', '2020-11-13 14:55:07'),
(58, 'GNC', 'panta alta', 0, 'Proteinas, suplementos, vitaminas, alimentos y bebidas saludables. General Nutrition Center la tienda de nutrición con gran variedad de productos para la salud, incluyendo vitaminas, minerales, suplementos para nutrición deportiva y otros.', '2222907667', NULL, '', '', NULL, NULL, NULL, 'gnc.com.mx', 'https://www.facebook.com/GNCMexico', 'https://www.instagram.com/gnc_mexico', 'https://twitter.com/gncmexico', 'gnc', 'activo', '2020-11-13 14:55:07'),
(59, 'ICYCLE', 'panta alta', 0, 'Pedalear el ritmo de la música. En cada clase de ICYCLE vivirás una experiencia de indoor cycling en donde puedes conectar mente y cuerpo. Además de ser un ejercicio completo y funcional de cardio y fuerza, llevarás tu cuerpo más allá de lo que piensas que es tu límite.', '2222146698', NULL, '', '', 'contacto@icycle.com.mx', NULL, NULL, 'icycle.com.mx', 'https://www.facebook.com/icyclemx', 'https://www.instagram.com/icyclemx', NULL, 'icycle', 'suspendido', '2020-11-13 14:55:07'),
(60, 'LINFOLAB', 'planta baja', 89, 'Nuestra misión es brindar a nuestros pacientes una experiencia única de atención, confort y Certeza Total en los servicios de análisis clínicos e imagenología.\r\n\r\nCompartimos contigo el orgullo de ser una empresa mexicana comprometida con la salud y el profesionalismo en servicios integrales de laboratorio.\r\nEn Linfolab Solesta contamos con distintos servicios para salvaguardar tu salud.', '2222907737', NULL, '', '2222436036', 'callcenter@linfolab.com', NULL, NULL, 'linfolabmexico.com.mx', 'https://www.facebook.com/linfolabmexico', 'https://www.instagram.com/linfolab_mexico', 'https://twitter.com/LINFOLAB_MEXICO', 'linfolab', 'suspendido', '2020-11-13 14:55:07'),
(61, 'MOOR SPA', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'moor_spa', 'suspendido', '2020-11-13 14:55:07'),
(62, 'REMATCH', 'panta alta', 10, 'Entrenamiento de alto rendimiento basado en la quema de grasa, aumento de masa muscular, tonificacion y enseñanza a comer bien.\r\nEjercicios como box, fuerza, resistencia, funcional, cardio, calistenia, TRX\r\nAceleramos resultados con sesiones reductivas de cavitacion, radiofrecuencia, electroestimulacion y presoterapia entre otros ademas de servicio de nutricion personalizada ', '5559443915', NULL, '5559443915', '5559443915', 'contacto@rematch.mx', NULL, NULL, 'rematch.mx', NULL, 'https://www.instagram.com/rematch.mx', NULL, 'rematch', 'suspendido', '2020-11-13 14:55:07'),
(63, 'SMART FIT', 'panta alta', 0, ' En un ambiente cómodo y sin presiones. Fue creado con el propósito de entregar fitness de alta calidad para todos.', NULL, NULL, '', '', NULL, NULL, NULL, 'smartfit.com.mx', 'https://www.facebook.com/SmartFitMx', 'https://www.instagram.com/smartfitmx', 'https://twitter.com/smartfitmx', 'smart_fit', 'activo', '2020-11-13 14:55:07'),
(64, 'STUDIO BY SOCO', 'panta alta', 0, 'Salón de belleza.', '2222907780', NULL, '', '', 'studiobysoco@gmail.com', NULL, NULL, 'studiobysoco.com', 'https://www.facebook.com/studiobysoco', 'https://www.instagram.com/studiobysoco', 'https://twitter.com/studiobysoc0', 'studio_by_soco', 'activo', '2020-11-13 14:55:07'),
(65, 'THE BARBER PLACE', 'planta baja', 129, 'Barberia.', '2222907785', NULL, '2225183956', '2222907785', 'thebarberplace@hotmail.com', NULL, NULL, 'the-barber-place-solesta.negocio.site', 'https://www.facebook.com/TheBarberPlaceSolesta', 'https://www.instagram.com/the_barberplace_puebla', NULL, 'the_barber_place', 'activo', '2020-11-13 14:55:07'),
(66, 'VINE VERA', 'panta alta', 0, 'Tratamientos faciales directo a tu hogar. Vine Vera Home nace para ofrecerte tratamientos faciales de lujo en la comodidad de tu hogar, no necesitas preocuparte por nada, solo reserva y disfruta.', '5552034192', '5555315438', '', '', 'atencion@vinevera.com.mx', NULL, NULL, 'vvmex.com.mx', 'https://www.facebook.com/Vine-Vera-M%C3%A9xico-286703745346708', 'https://www.instagram.com/vineveramx', NULL, 'vine_vera', 'suspendido', '2020-11-13 14:55:07'),
(67, 'BIZZARRO', 'panta alta', 50, 'Bizzarro es sinónimo de buen gusto, de joyas pensadas en materializar las emociones y sentimientos de nuestros clientes y ser un generador de momentos inolvidables. Nuestra gente, nuestros productos, nuestra pasión por el detalle, nuestros aliados comerciales, todo esto es Bizzarro, una marca llena de belleza y amor.', '2222907718', NULL, '', '2222907718', 'bpsolesta@bzr.com.mx', NULL, NULL, 'joyeriasbizzarro.com', 'https://www.facebook.com/JoyeriasBizzarroOficial', 'https://instagram.com/joyeriabizzarro', 'https://twitter.com/JoyeriaBizzarro', 'bizzarro', 'activo', '2020-11-13 14:55:07'),
(68, 'JOYERÍA CINCO ESTRELLAS', 'panta alta', 0, NULL, '9512101088', NULL, '', '', 'gpo_5estrellas@hotmail.com', NULL, NULL, NULL, 'https://www.facebook.com/joyeriacincoestrellasofficial', 'https://www.instagram.com/joyeriacincoestrellasoficial', NULL, 'joyeria_cinco_estrellas', 'suspendido', '2020-11-13 14:55:07'),
(69, 'JOYERÍA FANCY', 'panta alta', 56, 'Servicio de Reparación de Joyería y Grabado. Joyería y relojes.', '2221697270', NULL, '', '', 'info@fancyjoyeria.com', NULL, NULL, 'fancyjoyeria.com', 'https://www.facebook.com/fancyjoyeriapuebla', 'https://www.instagram.com/fancy_joyeria', NULL, 'joyeria_fancy', 'activo', '2020-11-13 14:55:07'),
(70, 'ÓPTICAS AMÉRICA', 'panta alta', 68, 'Ópticas América es una empresa 100% Oaxaqueña que abrió sus puertas en 1948, con una meta muy específica, buscar la excelencia en nuestros productos y servicios.\r\nFue fundada por el Sr. Antonio Gómez Bernardez, optometrista graduado en Nueva York, miembro de la academia de optometría de Estados Unidos de América. \r\nLa administración de esta empresa en el año de 1969 paso a manos de la Sra. María del Carmen Campos  en 1975 por la Sra. Ma. Eugenia Gómez Campos y en la actualidad la administración está a cargo del Opt. José Escobar Gómez. \r\nEn la actualidad somos una empresa con presencia a nivel nacional contando con puntos de venta en los estados de Oaxaca, Puebla, Chiapas, Tabasco, Veracruz, Tamaulipas, Coahuila,  Aguascalientes, Nayarit, Estado de México, Guerrero, Quintana Roo y Jalisco. \r\nTodo esto se ha logrado gracias al esfuerzo de todas las personas que día a día forman parte de esta empresa poniendo todo su empeño en cumplir nuestra misión, visión, política y objetivos de calidad para satisfacer las necesidades de nuestros clientes-pacientes. \r\nEl crecimiento de esta empresa se refleja en la apertura de sucursales que se inició a partir del año de 1975. En la actualidad contamos con 40 puntos de venta en toda la República Mexicana, todos ellos con buena ubicación.\r\nDespués de 68 años nuestra misión sigue siendo la misma “Atender las necesidades de salud visual a través de la comercialización de bienes y servicios ópticos con la más avanzada tecnología, el más alto sentido humano y excediendo las expectativas de nuestros clientes.”\r\nAdemás buscamos ser una fuente de trabajo en nuestra ciudad, para que no sólo los clientes obtengan beneficios, sino también proporcionamos trabajo que favorece el crecimiento del estado. \r\nLa matriz de Ópticas América se encuentra ubicada en la Av. Hidalgo 817, en el centro de la ciudad de Oaxaca, a pocos pasos de la plaza principal, el Zócalo.', '2222146697', NULL, '9513271653', '9513271653', 'communitymanager@opticasamerica.com', NULL, NULL, 'opticasamerica.com', 'https://www.facebook.com/opticas.america', 'https://www.instagram.com/opticasamerica', 'https://twitter.com/OpticasAmerica', 'opticas_america', 'suspendido', '2020-11-13 14:55:07'),
(71, 'OPTIKAL', 'panta alta', 27, 'Óptica. Productos Exclusivos. Examen visual Profesional. Innovaciones en lentes oftálmicas. Lanzamiento de nuevos productos. Productos oftálmicos de vanguardia tecnológica. Alianza con laboratorios oftálmicos.', '2222268759', NULL, '', '2222907652', 'solesta@optikalshop.com.mx', NULL, NULL, 'optikalshop.com.mx', 'https://es-la.facebook.com/OptikalKrono', 'https://www.instagram.com/optikalkronoshop', 'https://twitter.com/optikalkrono', 'optikal', 'suspendido', '2020-11-13 14:55:07'),
(72, 'RAY-BAN', 'panta alta', 41, 'Brindamos servicio de venta en gafas solares , armazones oftalmicos y gafas solares para niños.\r\n\r\nGafas solares y  oftalmicas.\r\n', '2907769', NULL, '2213619587', '2213619587', 'cesarwariza@gmail.com', NULL, NULL, NULL, 'https://www.facebook.com/rayban', 'https://www.instagram.com/rayban', NULL, 'ray_ban', 'activo', '2020-11-13 14:55:07'),
(73, 'TODO MODA', 'panta alta', 44, 'Dedicada a la producción y venta de accesorios para una mujer joven, trendy y dueña de su propio estilo.\r\n\r\nColección de productos a precios conveniente.', NULL, NULL, '', '5541640497', 'infomx@todomoda.com', NULL, NULL, 'mx.todomoda.com', 'https://www.facebook.com/TodoModaMex', 'https://www.instagram.com/todomoda_mexico/', 'https://twitter.com/todomoda_ar', 'todo_moda', 'suspendido', '2020-11-13 14:55:07'),
(74, 'VICTORINOX', 'panta alta', 74, 'Victorinox es una empresa familiar global dirigida actualmente por un miembro de la cuarta generación de la familia. La sede central de la empresa se encuentra en Ibach, cantón de Schwyz, en el corazón de Suiza. Fue allí donde Karl Elsener estableció su taller de cuchillería en 1884, y también inventó la “Original Swiss Army Knife” unos años más tarde. La empresa produce no sólo las mundialmente famosas navajas de bolsillo, sino también cuchillos domésticos y profesionales, relojes, equipaje y fragancias, de alta calidad.', '2222668359', NULL, '2227098613', '2222662731', 'grp.mx-ps.store1@victorinox.com', NULL, NULL, 'victorinox.com', 'https://www.facebook.com/VictorinoxMexico ', 'https://www.instagram.com/victorinoxmx', NULL, 'victorinox', 'activo', '2020-11-13 14:55:07'),
(75, 'AT&T', 'planta baja', 0, 'Teléfonos y navegación.\r\n<br>\r\nOfrecemos servicios móviles avanzados, navegación de alta velocidad y soluciones inteligentes para personas y empresas.', '2222146627', NULL, '2211762804', '8001010288', 'atencionclientesATT@customercare.att-mail.com', NULL, NULL, 'att.com.mx', 'https://www.facebook.com/ATT-Solesta-Puebla-107315071095910', 'https://www.instagram.com/attmx', 'https://twitter.com/ATTMx', 'att', 'suspendido', '2020-11-13 14:55:07'),
(76, 'BBVA', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'bbva', 'suspendido', '2020-11-13 14:55:07'),
(77, 'BERLITZ CENTRO DE IDIOMAS', 'panta alta', 0, 'Berlitz es un centro de idiomas con 140 años de experiencia con presencia en más de 70 países del mundo con más de 600 centros en cada uno, es la escuela líder de idiomas.', NULL, NULL, '', '', NULL, NULL, NULL, NULL, 'https://www.facebook.com/BerlitzPue', NULL, 'https://twitter.com/BerlitzMexico', 'berlitz_centro_de_idiomas', 'activo', '2020-11-13 14:55:07'),
(78, 'BEST BUY', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'best_buy', 'suspendido', '2020-11-13 14:55:07'),
(79, 'DJI', 'panta alta', 0, 'Inspírate desde una nueva perspectiva. DJI te invita a ver, tocar y aprender sobre sus innovadoras y creativas plataformas.', '2222907644', NULL, '', '', NULL, NULL, NULL, 'djistoremexico.com', 'https://www.facebook.com/DJIMexicoARS', 'https://www.instagram.com/djimexicooficial', 'https://twitter.com/DJIMexOficial', 'dji', 'activo', '2020-11-13 14:55:07'),
(80, 'AV PRESTIGE', 'panta alta', 23, 'Fabricante líder de sistemas de casas inteligentes y una compañía con crecimiento más rápido en el sector domótico en Europa. Presentes en 6 continentes y más de 100 países.', '2222907738', NULL, '2224098868', '2222907738', 'contacto@avprestige.com.mx', NULL, NULL, 'avprestige.com.mx', 'https://www.facebook.com/avprestigemx', 'https://www.instagram.com/fibaromx', 'https://twitter.com/FibaroMex', 'avprestige', 'suspendido', '2020-11-13 14:55:07'),
(81, 'MOBO SHOP', 'panta alta', 0, 'MOBO es la marca líder en la fabricación y distribución de accesorios para celulares en el mercado mexicano.\r\n<br><br>\r\nNuestra gama de productos se compone de una extensa variedad de artículos de protección, carga, audio, tecnología y accesorios para equipos móviles, además de contar con alianzas estratégicas con marcas reconocidas a nivel mundial como Motorola, Samsung y Apple.', NULL, NULL, '', '', 'atencionaclientes@mobo.mx', NULL, NULL, 'mobo.com.mx', 'https://www.facebook.com/MoboMexico', 'https://www.instagram.com/mobo_oficial', 'https://twitter.com/MoboMex', 'mobo_shop', 'activo', '2020-11-13 14:55:07'),
(82, 'MOVISTAR', 'panta alta', 0, 'En Telefónica México creemos que la tecnología debe estar al alcance de todos para mejorar la vida de las personas.\r\n<br><br>\r\nEsta visión es hoy una realidad. Especialistas de diferentes sectores nos definen como una organización de alto desempeño por ser líderes en la innovación de productos y servicios de telecomunicaciones bajo la marca Movistar, que se destaca por la calidad de servicio, cercanía con sus usuarios y las ofertas comerciales más atractivas del mercado.', NULL, NULL, '', '', NULL, NULL, NULL, 'movistar.com.mx', 'https://www.facebook.com/movistarmx', '', 'https://twitter.com/movistarmx', 'movistar', 'suspendido', '2020-11-13 14:55:07'),
(83, 'OFFICE MAX', 'planta baja', 131, 'Somos una cadena de artículos de oficina y papelería, líder en el ramo y con presencia de marca en varios países incluyendo:\r\nEstados Unidos, Canadá, México, Puerto Rico, Australia y Nueva Zelanda\r\n\r\nIniciamos operaciones en México en 1996, ofreciendo un amplio catalogo de productos de calidad y un servicio confiable que hoy por hoy nos ha colocado dentro de la preferencia de nuestro clientes, que van desde estudiantes y padres de familia; micronegocios y PYMES; hasta corporativos, instituciones educativas y de gobierno.', '2224215580', NULL, '2224215580', '2224215580', 'copymax.solesta@officemax.com.mx', NULL, NULL, 'officemax.com.mx', 'https://es-la.facebook.com/OfficeMaxMx', 'https://www.instagram.com/officemax_mx', 'https://twitter.com/officemax_mx', 'office_max', 'suspendido', '2020-11-13 14:55:07'),
(84, 'PRESSTO', 'planta baja', 90, NULL, '2222146608', NULL, '', '5552919929', 'jamc6707@outlook.com', NULL, NULL, 'pressto.com.mx', 'https://www.facebook.com/TintoreriasPresstoMexico', NULL, NULL, 'pressto', 'suspendido', '2020-11-13 14:55:07'),
(85, 'TELCEL', 'planta baja', 128, 'Pago contracion y renovación  de líneas Telcel, celulares, recargas, micas, cargadores.', '2222252539', NULL, '2228483633', '2228483633', 'plaza.solesta@viptelefonia.com.mx', NULL, NULL, 'vipglobal.mx', 'https://www.facebook.com/VipGlobalMx', 'https://www.instagram.com/vipglobalmx', NULL, 'telcel', 'suspendido', '2020-11-13 14:55:07'),
(86, 'DECOUPAGE', 'panta alta', 0, 'DECOUPAGE nace con la idea de generar ambientes únicos a partir de mobiliario y accesorios con gran personalidad.\r\n<br><br>\r\nDECOUPAGE es una técnica manual en la que se recortan elementos de distintos materiales y son pegados en muebles, vajillas y cojines. Esto representa al proyecto: diversos elementos de diferentes materiales, épocas, orígenes y estilos que se juntan para crear una propuesta irrepetible.\r\n<br><br>\r\nEl resultado es una mezcla equilibrada de los elementos menos predecibles que en conjunto, y gracias a una cuidadosa curaduría, generan espacios sofisticados, llenos de personalidad.\r\n<br><br>\r\nAdemás de muebles y accesorios provenientes de diferentes rincones del mundo, piezas recuperadas, únicas y orgánicas, en DECOUPAGE se diseñan muebles a medida, según las necesidades más específicas, para crear espacios personalizados.\r\n<br><br>\r\nEn DECOUPAGE se seleccionan los mejores materiales y se cuidan detalladamente los procesos de fabricación, asegurando así, una excelente calidad en cada uno de los productos. Esto, sumado a un excepcional servicio al cliente, resulta en una propuesta única.\r\n', '2229507173', '2229507174', '', '', 'solesta@decoupage.mx', '', 'https://goo.gl/maps/GwDJ228wffa7bXP49', 'decoupage.mx', 'https://www.facebook.com/decousolesta', 'https://www.instagram.com/dcpsolesta', NULL, 'decoupage', 'suspendido', '2020-11-13 14:55:07'),
(87, 'BED BATH & BEYOND', 'panta alta', 83, 'Visita nuestras tiendas y nunca sabrás lo que vas a encontrar: desde artículos básicos que no pueden faltar en tu hogar, hasta sorprendentes y novedosos productos que te facilitarán la vida.\r\n\r\nArtículos de cama, baño, cocina, electrodomésticos, decoración, jardín, terraza y mucho más que harán de tu casa tu lugar favorito', '2222250637', '', '', '8000239663', 'contactanos@bedbath.com.mx', NULL, NULL, 'bedbathandbeyond.com.mx', 'https://www.facebook.com/BedBathandBeyondMexico', 'https://www.instagram.com/bedbathandbeyondmexico', 'https://twitter.com/bedbathbeyondmx', 'bed_bath_and_beyond', 'activo', '2020-11-13 14:55:07'),
(88, 'CITY MARKET', 'panta alta', 0, 'Una experiencia diferente siempre abre el camino a mundos de notas, texturas y deleites desconocidos, haciendo que las posibilidades para disfrutar sean infinitas; por ello tienes que descubrir los más selectos y exquisitos productos para tu mesa, una experiencia gourmet que sólo City Market trae para ti.', NULL, NULL, '', '', NULL, NULL, NULL, 'citymarket.com.mx/comprasbiencitymarket', 'https://www.facebook.com/LaComerOficial/?fref=ts', 'https://www.instagram.com/citymarketmx/?hl=es', NULL, 'city_market', 'activo', '2020-11-13 14:55:07'),
(89, 'DUPUIS', 'panta alta', 11, 'Tienda de muebles y accesorios para Interior y Exterior de estilo contemporáneo con servicio de interiorismo gratuito. ', '2221794038', NULL, '2213569104', '2213569104', 'puebla@dupuis.com.mx', NULL, NULL, 'dupuis.com.mx', 'https://www.facebook.com/dupuis.puebla', 'https://www.instagram.com/dupuis_mx', NULL, 'dupuis', 'activo', '2020-11-13 14:55:07'),
(90, 'GAIA', 'panta alta', 8, 'GAIA es la marca de muebles y accesorios de diseño adaptados al estilo de vida urbano. En GAIA puedes comprar de forma rápida, fácil y segura tus productos preferidos para tu casa: te ofrecemos una gran variedad de productos, desde sofás, sillas, cajoneras, cómodas, burós, mesas, escritorios, tapetes, lámparas, textiles, cuadros y accesorios en varios estilos como contemporáneo, tradicional, artesanal, industrial o con un toque retro. Son piezas de madera y otros materiales creadas por nuestro equipo de diseñadores, además de una gran variedad de piezas seleccionadas por nuestros interioristas, inspiradas en la ciudad. <br><br>Te proponemos diseños simples y modernos, con soluciones versátiles adaptadas a tus espacios como el comedor, salas, recámaras, estudio y oficina, y a las necesidades actuales de tu estilo de vida. Nuestra misión es que puedas sentirte parte de la ciudad donde vives desde cualquier lugar, pero sobre todo, comenzando desde tu hogar.', '5564141153', NULL, '5564141153', '5553501425', 'hola@gaiadesign.com.mx', NULL, NULL, 'gaiadesign.com.mx', 'https://www.facebook.com/gaiadesignmexico', 'https://www.instagram.com/gaiadesignmx', 'https://twitter.com/gaiadesignmx', 'gaia', 'suspendido', '2020-11-13 14:55:07'),
(91, 'IKARUS', 'panta alta', 0, 'Hacemos de tu idea algo único. Llevamos el concepto de interiorismo mas allá de un espacio, creamos identidad en cada uno de nuestros diseños.\r\n<br><br>\r\nIkarus tiene  una visión de calidad y motivados por la funcionalidad, practicidad y de impecable diseño, nuestras cocinas buscan garantizar tu comodidad sin olvidar las tendencias actuales que confluyen modernidad, lujo y eficiencia en espacios.', '2222907767', NULL, '', '', 'ventas@ikarus.mx', NULL, NULL, 'ikarus.mx', 'https://www.facebook.com/IkarusInteriorismo', 'https://www.instagram.com/ikarus_cocinas', 'https://twitter.com/ikarusmx', 'ikarus', 'activo', '2020-11-13 14:55:07'),
(92, 'MARTHA SOPHIA', 'panta alta', 20, 'El significado de las flores y las plantas en nuestras vidas va mucho más allá de una admiración y aprecio por la belleza de la naturaleza, implica todo lo que podemos expresar y crear a través del lenguaje floral, escenográfico y paisajístico. Nuestro trabajo es dar vida y alma a los espacios en lo que pasamos gran parte de nuestro tiempo.', '2222907630', '5536031357', '5548908582', '', 'pedidos@marthasophia.com', NULL, NULL, 'marthasophia.com', 'https://www.facebook.com/MarthaSophiaFlores', 'https://www.instagram.com/martha.sophia', 'https://twitter.com/marthasophia7', 'martha_sophia', 'activo', '2020-11-13 14:55:07');
INSERT INTO `locales` (`id`, `nombre`, `planta`, `numero_local`, `descripcion`, `telefono_1`, `telefono_2`, `whatsapp`, `telefono_atencion_clientes`, `correo_electronico`, `ubicacion`, `url_ubicacion`, `url_pagina`, `url_facebook`, `url_instagram`, `url_twitter`, `url`, `estatus`, `fecha_registro`) VALUES
(93, 'MUMUSO', 'panta alta', 34, 'Convertir cada minuto de la vida, en un momento memorable a través del diseño innovador, calidad en el producto y una experiencia de compra única.', '2221794091', '2221794091', '', '2221794091', 'm18@lob.com.mx ', 'Primer piso SA-07', 'https://goo.gl/maps/sePFRaPS2oibi3aT8', 'mumusomx.com', 'https://www.facebook.com/mumusomx', 'https://www.instagram.com/mumuso_mx', 'https://twitter.com/mumuso_mx', 'mumuso', 'activo', '2020-11-13 14:55:07'),
(94, 'MOBILE OUTFITTERS', 'planta baja', 0, 'Protección y Personalización para cualquier dispositivo electrónico.\r\n\r\nProtección Telefonica.', NULL, NULL, '', '', 'contacto@mobileoutfittersmexico.com', NULL, NULL, NULL, 'https://www.facebook.com/mobileoutfitterspuebla', 'https://www.instagram.com/mobileoutfitterspuebla', NULL, 'mobile_outfitters', 'suspendido', '2021-03-13 09:35:25'),
(95, 'FIX IT', 'planta baja', 0, 'FIX IT desde 2015. Somos una empresa orgullosamente mexicana, con más de 15 años de experiencia en reparación de celulares. Somos líderes a nivel nacional con más de 100 sucursales en toda la república (en continuo proceso de expansión) y más de 24,000 reparaciones promedio por año, contamos con los técnicos certificados más especializados y expertos de todo el país en reparaciones de hardware (a nivel componente) y software en general. Obtén un servicio exprés, seguro, altamente demandado y a precios súper competitivos. FIX IT #1 de México.\r\n\r\nFIX IT, los expertos en reparación de celulares.', '2222146775', NULL, '', '5578250728', 'sugerencias@fixitmexico.com.mx', NULL, NULL, 'fixitmexico.com.mx', 'https://www.facebook.com/Fixit-M%C3%A9xico-162936631074271', 'https://www.instagram.com/fixit_oficial', 'https://twitter.com/OficialFixit', 'fix_it', 'suspendido', '2021-03-13 09:36:01'),
(96, 'DOROTHY GAYNOR', 'panta alta', 52, 'Caminamos junto con ellos a sus: viajes, entrevistas, comidas y citas. Desde que se fundó nuestra empresa y hasta el día de hoy, el objetivo ha sido el mismo: ser el destino #1 en zapatos para que nuestros clientes siempre encuentren su par favorito ante cualquier necesidad y estilo.\r\n\r\nNos seguimos expandiendo año con año para poder estar más cerca de ti. Hoy contamos con más de 100 tiendas a lo largo de la República Mexicana y además de contar con nuestra tienda online, de manera que estamos contigo con un sólo “clic”.Somos una empresa que respira gracias al trabajo y dedicación de más de 800 empleados, quienes dan todo por satisfacer las necesidades de nuestros clientes.\r\n\r\nSomos el  destino #1 en zapatos para que nuestros clientes siempre encuentren su par favorito ante cualquier necesidad y estilo.', '2223997411', NULL, '', '2223997411', 'ayuda@dorothygaynor.com', NULL, NULL, 'dorothygaynor.com', 'https://www.facebook.com/DorothyGaynorOficial', 'https://www.instagram.com/dorothygaynor', NULL, 'dorothy_gaynor', 'suspendido', '2021-03-13 09:36:34'),
(97, 'GO STORE', 'panta alta', 0, 'Además de ser una gran oportunidad de negocio, también busca agilizar el proceso de compra venta. A través de este pick up, ya no tendrás que hacer entregas en diferentes lugares y tiempos, esto brindara confianza a tus clientes que están haciendo una compra segura.\r\n\r\nGo Mom tiene como objetivo principal: hacer crecer tu negocio, mejorando la manera de ofrecer y acceder a los productos.', '2211064153', NULL, '2211064153', '2215691732', 'gomompickup@gmail.com', NULL, NULL, 'https://www.facebook.com/Go-mom-417919818962025', 'https://instagram.com/gomompickup?igshid=1qh9q8cx96utb', 'https://instagram.com/gomompickup', NULL, 'go_store', 'suspendido', '2021-03-13 09:37:01'),
(98, 'NUTRISA', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'nutrisa', 'suspendido', '2021-03-13 13:57:39'),
(99, 'LINEA PURA', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'linea_pura', 'suspendido', '2021-03-13 13:58:23'),
(100, 'EUREKAKIDS', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, 'eurekakids.es', NULL, NULL, NULL, 'eurekakids', 'suspendido', '2021-03-13 13:58:52'),
(101, 'MUY MUCHO', 'panta alta', 0, 'Artículos de decoración para el hogar y regalos.', '5530418511', '2222570973', '', '', 'muymuchosolesta@gmail.com', NULL, NULL, NULL, 'https://www.facebook.com/muymuchomexico', 'https://www.instagram.com/muymuchomexico', NULL, 'muy_mucho', 'activo', '2021-03-13 13:59:27'),
(102, 'CANADIAN SCHOOL EARLY YEARS', 'panta alta', 0, 'Canadian School Early Years brinda a tus hijos un programa de aprendizaje vanguardista con inmersión total al inglés y una sólida formación en valores, el cual está basado y acreditado por el Ministerio de Educación de Alberta, Canadá. Contamos con maestros nacionales e internacionales en permanente capacitación con un alto sentido humano y compromiso de formar. Nuestras aulas y espacios son seguros, cálidos y recreativos para desarrollar e impulsar su conocimiento y talentos. \r\n<br><br>\r\nNuestros alumnos crecen en una comunidad unida, integrada por  padres de familia y colaboradores quienes en conjunto formamos niños felices que trascienden y se preparan diariamente para tener éxito y transformar el mundo siendo ciudadanos éticos e internacionales.\r\n', '2214364492', NULL, '2214364492', '2214364492', NULL, NULL, NULL, 'canadianschoolpuebla.com.mx', 'https://www.facebook.com/canadianschoolpue', 'https://www.instagram.com/canadianschoolmex', 'https://twitter.com/canadianoficial', 'canadian_school', 'activo', '2021-05-21 13:17:50'),
(103, 'HAVOC', 'planta baja', 0, 'En Havoc nos encanta verte lucir extraordinario y alcanzar tu máximo potencial, es por ello que confeccionamos las mejores prendas a la medida y personalizadas por ti y para ti, ya sea para un evento, como puede ser tu propia boda o una graduación, hasta el día a día en la oficina o homeoffice. Conoce nuestros showrooms en CDMX, Guadalajara y Monterrey para que uno de nuestros consultores de imagen pueda tomar tus medidas y pueda también brindarte las mejores opciones con base en gustos, preferencias y más!', '5571000666', NULL, '5553516892', '5571000666', 'hola@havoc.mx', NULL, NULL, 'havoc.mx', 'https://www.facebook.com/HavocSuits', NULL, NULL, 'havoc', 'activo', '2021-10-05 17:42:33'),
(104, 'LA CHANCHA Y LOS 20', 'planta baja', 0, 'Restaurante Argentino, te ofrecemos un amplio menú que incluye entradas, ensaladas, sopas, pastas, cortes, parrillas, postres, cafés, tes, destilados y vinos a precios justos siempre cuidando la calidad y el servicio.', '2216363609', NULL, '2216363609', '2216363609', 'gerencia@lachanchaylos20.com.mx', NULL, 'https://goo.gl/maps/QJd6NzaEdHq6sNBF7', 'lachanchaylos20.com.mx', 'https://www.facebook.com/lachanchaylos20mx', 'https://www.instagram.com/lachanchaylos20mx', NULL, 'lachanchaylos20', 'activo', '2021-10-05 17:47:52'),
(105, 'DENTALIA', 'planta baja', 0, 'En dentalia® queremos verte feliz, por ello contamos con diferentes tratamientos que se adaptan perfecto a tus necesidades, estilo de vida y presupuesto. Somos líderes en el mercado de beneficios dentales con más de 60 clínicas.', '8000033682', NULL, '', '8000033682', 'hola@dentalia.com', NULL, 'https://goo.gl/maps/jFAo8fRJbQ738Zq6A', 'dentalia.com', 'https://www.facebook.com/dentalia.mx', 'https://www.instagram.com/dentalia_mx', 'https://twitter.com/dentalia_mx', 'dentalia', 'activo', '2021-10-05 18:01:44'),
(106, 'EL GRILLO', 'panta alta', 0, 'el grillo es un restaurante de comida mexicana moderno y novedoso, que busca con cada platillo y coctelería sorprender a nuestros clientes, brindarles cosas diferentes y divertirlos en cada momento, somos parte de grupo Forchetta, un grupo restaurantero conocido en todo México, con mas de 30 años de experiencias, esta nueva versión del grillo viene capitaneada por el chef Ángel Vásquez. con opciones de mariscos, tacos, platos tradicionales mexicanos y los mejores postres, te aseguramos que no podrás resistir el visitarnos y quedarte con nosotros.', '2222272909', NULL, '3331895389', '2222272909', 'smb@grupoforchetta.com.mx', NULL, NULL, NULL, NULL, 'https://www.instagram.com/el_grillomx', NULL, 'elgrillo', 'suspendido', '2021-10-05 18:04:33'),
(107, 'SIWA BEAUTY BAR', 'panta alta', 0, 'Belleza, cosmética y cuidado personal.\r\n\r\nMasajes, Faciales, Reductivos Con Aparatologia, Mani, Pedi, Extensiones De Pestañas, Depilación Con Cera, Paquetes Siwa Party & Bride To Be.\r\n', '222 257 0989', NULL, '222 257 0989', '222 257 0989', 'siwabeautybar@gmail.com', NULL, NULL, NULL, 'https://www.facebook.com/SIWA-beauty-bar-100489599136439/', 'https://www.instagram.com/siwa_beautybar/', NULL, 'siwa', 'activo', '2022-02-11 12:31:40'),
(108, 'IMORIEDU ROBOLAB', 'panta alta', 75, 'EDUCACION Y DIVERSION TODO EN UN SOLO LUGAR. ROMPECABEZAS, ALCANCIAS, ROBOTS SOLARES, ARMABLES, ROBOT INTERACTIVO, X CUBE.', '2222907538', '2212035329', '', '2222907538', 'imoripuebla@gmail.com', NULL, NULL, 'imotiedu.net', 'facebook.com/IMORI-EDU-Puebla-105527012024879', NULL, NULL, 'imoriedu', 'suspendido', '2022-02-17 19:38:58'),
(109, 'OAKBERRY', 'panta alta', 0, 'Asai Bowls, Smoothies, Healthy Fast Food, Toppings.', '', '', '', '', 'oakberrypuebla@gmail.com', NULL, NULL, '', '', NULL, NULL, 'oakberry', 'suspendido', '2022-02-25 07:28:58'),
(110, 'AZUR', 'panta alta', 37, 'Restaurante de comida mediterránea\r\n\r\nCocina inspirada en sabores mediterráneos con matices actuales, en una atmósfera acogedora, donde además de comer, ¡vivirás una experiencia inolvidable!', '2226883092', '2226883021', '2225415521', '2225415521', 'coneversion_creativa@outlook.com', NULL, NULL, NULL, 'https://www.facebook.com/azurrestaurantepuebla', 'https://www.instagram.com/azur_puebla', NULL, 'azur', 'activo', '2022-03-25 17:51:21'),
(111, 'HERON', 'panta alta', 0, 'Chamarras de piel de alta calidad, chamarras de piel de personajes famosos, tradicionales y accesorios de piel hechos en México desde el 2008.', '2226222101', NULL, '522211052715', '', 'explanada_puebla@heron-leathers.com', NULL, NULL, 'heron-shop.com.mx', 'https://www.facebook.com/HeronMexico', 'https://www.instagram.com/heron_mexico', NULL, 'heron', 'activo', '2022-06-09 00:00:00'),
(112, 'KRISPY KREME', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, 'https://www.krispykreme.mx/', 'https://www.instagram.com/krispykrememexico', 'https://www.facebook.com/krispykrememex', 'https://x.com/MexKrispyKreme', 'krispy_kreme', 'activo', '2022-06-09 00:00:00'),
(113, 'GUINDA DE PANA', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'guinda_de_pana', 'suspendido', '2022-06-09 00:00:00'),
(114, 'GONG CHA', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, 'https://gongcha.mx/', 'https://www.facebook.com/gongchamex', 'https://www.instagram.com/gongchamex/', 'https://x.com/Gongchamex', 'gong_cha', 'activo', '2022-06-09 00:00:00'),
(115, 'BISQUETS OBREGÓN ', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, 'https://bisquetsobregon.com/https://bisquetsobregon.com/', 'https://www.facebook.com/bisquetsobregonoficial/', 'https://www.instagram.com/bisquetsobregon/', 'https://x.com/bisquetsobregon', 'bisquets', 'activo', '2022-06-09 00:00:00'),
(116, 'MÓBICA', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mobica', 'suspendido', '2022-06-09 00:00:00'),
(117, 'HOTARU', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hotaru', 'suspendido', '2022-07-06 12:50:51'),
(118, 'THE MINS', 'panta alta', 21, 'Playground inmersivo, tecnología interactiva, retos de aventura, salón de fiestas, concept store y food court.\r\n\r\nSomos un Fun Center temático con playground inmersivo, retos de aventura y tecnología interactiva para niños de 2 a 12 años. Acompáñanos a vivir esta experiencia junto a los Mins BUDJAK, RUN, DI  y ALT. Tenemos food court y área para fiestas infantiles y eventos.', '2222257314', NULL, '2213444875', '2222257314', 'themins.contacto@gmail.com', NULL, 'https://goo.gl/maps/3vfcQBjQtzLr6UR97', 'themins.mx', 'http://facebook.com/theminsmx/', 'https://instagram.com/theminsmx/', NULL, 'the_mins', 'activo', '2022-10-06 12:29:42'),
(119, 'CALLEJÓN GEEK', 'panta alta', 23, 'Somos una tienda dedicada al mundo de los Coleccionables desde funkos, Bandai, Loungefly, play arts hasta hoy toys. \r\nTe traemos todos los dulces asiáticos más deliciosos hasta Puebla.\r\nCallejón Geek dónde la edición especial eres tú.\r\nFunko - Coleccionables - Dulces Asiáticos', '2211648525', NULL, '2211648525', '2211648525', 'callejon.geek.coleccionables@gmail.com', NULL, NULL, NULL, 'https://www.facebook.com/ElCallejonGeek/', 'https://www.instagram.com/elcallejongeek/', NULL, 'callejon_geek', 'activo', '2022-10-31 10:05:44'),
(120, 'BATTE QUE BATTE', 'panta alta', 42, 'Somos una repostería saludable. Hacemos tus postres favoritos en su versión más saludable. Todos nuestros productos sin azúcar añadido, aptos para diabéticos, keto, sin lácteos y sin gluten.', '2222760663', NULL, '2222760663', '2222760663', 'battequebattefoodtruck@gmail.com', NULL, 'https://goo.gl/maps/kGedHyw4ZA4K3nSr5', 'linktr.ee/battequebatte', 'https://www.facebook.com/battequebatte', 'https://www.instagram.com/battequebatte', '', 'battequebatte', 'activo', '2022-11-14 11:05:18'),
(121, 'PITSHOP', 'panta alta', 2, 'Libera tu piloto interior en PITSHOP México, una boutique deportiva de fórmula 1 con diferentes marcas como: Red Bull, Mercedes, Ferrari, McLaren, Aston Martin y Alfa Romeo.', '2224315196', NULL, '2221626286', '2224315196', NULL, NULL, NULL, NULL, 'https://www.facebook.com/PitshopMexico/', 'https://www.instagram.com/pitshopmexicof1/?hl=en', NULL, 'pitshop', 'activo', '2023-10-23 11:39:52'),
(122, 'XTORE', 'panta alta', 2, 'XTORE es una tienda de equipo de cómputo especializado para negocios, en donde amablemente te atienden expertos, además ofrecemos servicios de reparación y mantenimiento.', '2222252201', NULL, '', '2222252201', 'clientes@xtore.mx', NULL, '	https://maps.app.goo.gl/aFpovN8SE7xnPvjf9			', 'xtore.mx', NULL, 'https://www.instagram.com/xtoresolesta?igsh=MW5nM2V4eHgxbWVkNQ==', NULL, 'xtore', 'activo', '2023-10-27 11:39:52'),
(123, 'BLANCO AZÚCAR', 'panta alta', 0, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, 'https://www.facebook.com/blancoazucar/', 'https://www.instagram.com/blancoazucar/', NULL, 'blanco_azucar', 'activo', '2024-01-03 17:18:48'),
(124, 'MAESTRO OSO TACOS & BEER', 'planta baja', 0, 'Restaurante con servicio de alimentos y bebidas y tacos', '2229843126', '2222257520', '2222257520', '2222257520', 'elosotacos.beer@gmail.com', NULL, 'https://maps.app.goo.gl/q48TPbToX1omNWoN6', NULL, 'https://www.facebook.com/maestro.osopuebla', 'https://www.instagram.com/maestro.oso', NULL, 'maestro_oso', 'activo', '2024-03-04 12:41:08'),
(125, 'MILANO', 'planta baja', 6, 'Centro de entrenamiento de replicas de aire.', '2216346242', '2223923405', '2216346242', '2216346242', NULL, NULL, NULL, NULL, NULL, 'https://www.instagram.com/milanopuebla', NULL, 'milano', 'activo', '2024-03-04 12:41:08'),
(126, 'SINSOMBRERO', 'panta alta', 52, 'Cocina de Autor', '2222253584', NULL, '', '2211167457', 'contacto@gruposeratta.mx', NULL, 'https://maps.app.goo.gl/cWNbDZoC6gKDJaXM6', 'gruposeratta.mx', 'https://www.facebook.com/profile.php?id=100094527766738', 'https://www.instagram.com/sinsombrero.mx', NULL, 'sinsombrero', 'activo', '2024-03-04 12:41:08'),
(127, 'NORDAY', 'planta baja', 7, 'Venta de Termos de acero, marca mexicana, se personalizan al momento.', '2211093778', '2211013396', '2211093778', '2211093778', 'ventas@nordaypuebla.com', NULL, 'https://maps.app.goo.gl/YMcdSbfBHuUkhYL16', 'nordaypuebla.com', 'https://www.facebook.com/nordaypuebla', 'https://www.instagram.com/nordayshop_puebla', NULL, 'norday', 'activo', '2024-03-04 12:41:08'),
(128, 'VRACE', 'planta baja', 8, 'Simuladores de Carreras F1 y Realidad Virtual', '2215753107', NULL, '2215753107', '2215753107', 'vracemx@gmail.com', NULL, 'https://maps.app.goo.gl/zcpWCrrXGinS5N4F7', NULL, 'https://www.facebook.com/vracemx', 'https://www.instagram.com/vrace.mx', NULL, 'vrace', 'activo', '2024-03-04 12:41:08'),
(129, 'FORST', 'planta baja', 68, 'CALZADO Y ROPA DEPORTIVA', '2222146659', NULL, '', '', 'on2@mtsport.com.mx', '', 'https://maps.app.goo.gl/Epirx4JaMhz9omSG8', 'forst.mx', NULL, NULL, NULL, 'forst', 'activo', '2024-03-13 17:01:40'),
(130, 'SABINOS', 'planta baja', 109, 'Restaurante Mexicano de Vanguardia', '2224023254', NULL, '2224023254', '', '', NULL, NULL, 'www.sabinos.mx', 'https://www.facebook.com/share/VNtY6nrK8PAYxxoF/?mibextid=hu50Ix', 'https://www.instagram.com/sabinos.mx?igsh=MWJjYTloMm16d2huaw==', NULL, 'sabinos', 'activo', '2024-11-11 17:46:00'),
(131, 'LESTER COLCHONES', 'planta baja', 40, 'Lester es una empresa que se fundó en Puebla en 1967.   Desde el principio el principal objetivo ha sido siempre la calidad, y es por ello que se ha posicionado como referente en el sector, siendo la primera empresa de colchones en obtener el certificado ISO de calidad.', '2229822010', NULL, '2224294507', '', '', NULL, NULL, 'https://lester.mx/', 'https://www.facebook.com/ColchonesLester/?locale=es_LA', 'https://www.instagram.com/lestercolchones/?hl=es', NULL, 'lester_colchones', 'activo', '2024-06-11 18:46:00'),
(132, 'Choupinet', 'panta alta', 17, 'Marca de ropa y accesorios para niños y bebés. ', '2222907723', NULL, '5522462416', '', 'pedidos@choupinet.mx', NULL, NULL, 'https://choupinet.com', 'https://www.facebook.com/choupinet.mx', 'https://www.instagram.com/choupinet.mx/', 'twitter.com/AlboaMX', 'choupinet', 'activo', '2024-06-11 18:55:07'),
(133, 'SÚPER PALETERÍA MARY BARRAGÁN', 'panta alta', 67, 'Más de 106 sabores de helados, nieves paletas y aguas frescas en un mismo lugar!!\r\n', '', NULL, '', '', '', NULL, NULL, '', '', '', '', 'super_paleteria_mary_barragan', 'activo', '2024-06-11 18:55:07'),
(134, 'Hudson', 'planta baja', 121, 'Restaurante americano de hamburguesas', '2212516969', '2212516969', '2212516969', '2212516969', 'contacto@hudsonburgers.mx', 'Atlixcáyotl, Reserva Territorial Atlixcáyotl, Centros Comerciales Desarrollo Atlixcayotl, 72193 Heroica Puebla de Zaragoza, Pue.', 'https://g.co/kgs/2iSq9nw', 'http://hudsonburgers.mx/', 'https://www.facebook.com/Hudsonburgers.mx/', 'https://www.instagram.com/hudsonburgers.mx/', 'https://x.com/hudsonburgers.mx/', 'hudson', 'activo', '2024-06-11 18:55:07'),
(135, 'Hotaru Puebla', 'panta alta', 5, '\r\nHotaru® es una barra enfocada en exponer las cualidades y virtudes del sushi contemporáneo.\r\nUn espacio solemne que celebra su experiencia en cada nigiri y entrada. La armonía, precisión y proyección de la naturaleza pura de pescados, mariscos, arroces, trufas e ingredientes especiales dentro de una presentación extraordinaria.\r\n\r\nHotaru® es una experiencia única para los verdaderos fanáticos de la alta cocina y del sushi. Ofrece en sus platillos pescados y mariscos de primera calidad y provenientes de diversas partes de mundo: Japón, España, Nueva Zelanda, Islandia, Escocia, Rusia, California, Alaska, Canadá, y gran parte del Golfo de México y del Pacífico.', '2222146754', NULL, '2216610038', '', 'hotaru.puebla@grupocosteno.com', NULL, '', 'https://costeno.com/hotaru/', 'https://www.facebook.com/hotarupuebla', 'https://www.instagram.com/hotarupuebla/', '', 'hotaru_puebla', 'activo', '2024-06-11 18:55:07'),
(136, 'Wing\'s Army', 'panta alta', 36, 'Restaurante - Bar, totalmente familiar, alitas, ensalada, Boneles, Burguers y Cervezas Importadas, Ideal para convivir en familia y/o disfrutar de los eventos deportivos. Terraza, planta y planta baja, todos los espacios con TV y Sonido', '2222467348', NULL, '221 848 1097', '', 'wasolesta@gmail.com', NULL, '', 'https://www.wings-army.com/', 'https://www.facebook.com/WingsArmyPuebla', NULL, NULL, 'wings_army', 'activo', '2024-09-05 18:55:07'),
(137, 'El Tiros Caps', 'planta baja', 10, 'Somos una marca de gorras que creamos modelos urbanos y con el  mejor estilo propio, además somos una tienda que trabaja con distintas marcas de gorras teniendo los mejores lanzamientos y modelos actuales.', '2226227651', NULL, '2215802667', '', NULL, NULL, '', 'https://eltiroscaps.com/', 'https://www.facebook.com/ElTirosCaps/?locale=es_LA', 'https://www.instagram.com/el_tiros_caps/', NULL, 'el_tiros_caps', 'activo', '2024-09-05 18:55:07'),
(138, 'Sushi Seven', 'panta alta', 66, 'En Sushi Seven creamos la atmósfera propicia para ofrecer a nuestros clientes comida de la más alta calidad, ambiente atractivo y cómodo; donde disfrutar de nuestra variedad de platillos será una experiencia única, fresca y creativa.', '222 290 3891', NULL, '221 409 0803', '', NULL, NULL, '', 'https://www.sushiseven.com.mx/', 'https://www.facebook.com/share/SrJoMJT261uEGp8m/?mibextid=qi2Omg', 'https://www.instagram.com/sushisevenmx?igsh=ZHk2M2F1emFob3E3', NULL, 'sushi_seven', 'activo', '2024-09-05 18:55:07'),
(139, 'Il Grissini', 'panta alta', 1, 'Restaurante de “Cocina Italiana artesanal” con pastas y pizzas de masa madre hechas al día, postres emblemáticos, una oferta de vinos de alta especialidad y coctelería de moda.', '5522130907', NULL, '5522130907', '', NULL, NULL, '', 'https://www.citymarket.com.mx/comprasbiencitymarket/', NULL, 'https://www.instagram.com/citymarketmx/', NULL, 'il_grissini', 'activo', '2024-09-03 11:55:07'),
(140, 'Panareo', 'panta alta', 44, 'La masa de nuestras pizzas se elabora diariamente y reposa durante 30 horas a temperatura ambiente antes de poder hornearla para ti en un horno a 450° de temperatura durante 90 segundos', '2226222829', NULL, '2224697001', '', 'panareopizza@gmail.com', 'Atlixcáyotl 4931-Local 44, Reserva Territorial Atlixcáyotl, 45 y 46, 72193 Heroica Puebla de Zaragoza, Pue.', 'https://maps.app.goo.gl/1HvQKs6rUXrpKbHQ9', NULL, 'https://www.facebook.com/panareopizza', 'https://www.instagram.com/panareopizza/', NULL, 'panareo', 'activo', '2024-10-07 11:55:07'),
(141, 'PortSaid', 'panta alta', 41, 'Spa para el cuidado de la piel Centro de cuidado y bienestar para la piel. Tratamientos especializados para cada tipo de rostro, mejora la experiencia de un tratamiento facial con nosotros y descubre el cuidado de la piel con una atención especializada en ti con productos de alta gama con minerales y polvo de meteorito.', '2228530167', NULL, '2228530167', '', NULL, 'Atlixcáyotl 49-31, Reserva Territorial Atlixcáyotl, Centro Comercial Angelopolis, 72193 San Bernardino Tlaxcalancingo, Pue.', 'https://maps.app.goo.gl/73g97KP6Yh873LhF6', 'https://portsaidcosmetics.com/', 'https://www.facebook.com/people/Portsaid-Puebla', 'https://www.instagram.com/portsaid.cosmetics/', NULL, 'portsaid', 'activo', '2024-10-07 11:55:07'),
(142, 'Pixxi', 'panta alta', 30, 'Somos una tienda de cosmética y accesorios de moda a un precio accesible. Ponemos a tu disposición una gran variedad de productos de excelente calidad.', '2224880162', NULL, '2221144543', '', 'solestapixxi@gmail.com', 'Atlixcáyotl 4931-Local 30, Reserva Territorial Atlixcáyotl, Centros Comerciales Desarrollo Atlixcayotl, 72193 Heroica Puebla de Zaragoza, Pue.', 'https://maps.app.goo.gl/eJeY7Hg5Nyty6TBU8', NULL, 'https://www.facebook.com/pixximexico', 'https://www.instagram.com/pixximexico/', NULL, 'pixxi', 'activo', '2024-10-07 11:55:07'),
(143, 'Dendera', 'panta alta', 33, 'Conoce a los tatuadores del Team DENDERA |Tatuadores con más 7 años de experiencia en el mundo del tatuaje, conoce su trabajo ', NULL, NULL, '', '', 'dendera.co@gmail.com', 'Centro Comercial Solesta Local L-26 Reserva Territorial Atlixcayotl 4931, 72193 Heroica Puebla de Zaragoza, Pue.', 'https://maps.app.goo.gl/LCMEo2952ojJkYcx7', NULL, NULL, 'https://www.instagram.com/dendera.co/', NULL, 'dendera', 'activo', '2024-10-07 11:55:07'),
(144, 'Cervecería La Bici de Cleta', 'panta alta', 53, 'Bar Poblano donde la Cerveza y destilados son los principales atractivos.Cuenta con una amplia gama de alimentos que puedes disfrutar y esta ubicado en una de las zonas mas importantes y transitadas de Puebla.', '2224316955', NULL, '2211402642', '', 'gerpuesolesta@bicidecleta.com', 'Atlixcáyotl 1899, Reserva Territorial Atlixcáyotl, Corredor Comercial Desarrollo Atlixcayotl, 72820 Heroica Puebla de Zaragoza, Pue.', 'https://maps.app.goo.gl/7DqMLNuoGZQe9FE3A', 'https://labicidecleta.com/menu/', 'https://www.facebook.com/labicidecletasolesta', 'instagram.com/labicidecleta/', NULL, 'cbc', 'activo', '2024-10-07 11:55:07'),
(145, 'Nitro', 'planta baja', 125, 'Clínica de rehabilitación y acondicionamiento funcional. Clases semi personalizadas. ', '2221572699', NULL, '2221572699', '', 'contacto@nitrotrainingclub.com', 'Atlixcáyotl 4931-Local 1 y 2, Reserva Territorial Atlixcáyotl, Centros Comerciales Desarrollo Atlixcayotl, 72193 Heroica Puebla de Zaragoza, Pue.', 'https://maps.app.goo.gl/M7ak3FPjL4X8AHSw7', NULL, NULL, 'https://www.instagram.com/nitro_functionalclub/', NULL, 'nitro', 'activo', '2024-10-07 11:55:07'),
(146, 'Searena', 'panta alta', 72, 'Empresa mexicana fundada en 2020, considerada una marca de lujo especializada en la confección de prendas para destinos turísticos, fabricadas en Italia', '2221143689', NULL, '2224383849', '', 'searenadorado@gmail.com', '', 'Vía Atlixcayotl. 4931. Col. Centros Comerciales Desarrollo Atlixcayotl Solesta, Manzana L-72 Planta Alta, 72193 Heroica Puebla de Zaragoza, Pue.', 'http://searena.mx/', NULL, 'https://www.instagram.com/searena.pue', NULL, 'searena', 'activo', '2025-10-14 11:55:07');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `locales`
--
ALTER TABLE `locales`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `locales`
--
ALTER TABLE `locales`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=147;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
